version: '3'

services:
  eureka:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8761:8761'
    working_dir: /eureka-server
    volumes:
      - ./eureka-server:/eureka-server
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    working_dir: /api-gateway
    volumes:
      - ./api-gateway:/api-gateway
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  user-profiles-api:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8081:8081'
    working_dir: /user-profiles-api
    volumes:
      - ./user-profiles-api:/user-profiles-api
    depends_on:
      - eureka
      - postgresdev
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev
  chat-history:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8082:8082'
    working_dir: /chat-history
    volumes:
      - ./chat-history:/chat-history
    depends_on:
      - eureka
      - postgresdev
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev